export const CalendarActionTypes = {
  CREATE_CALENDAR: 'CREATE_CALENDAR',
  REMOVE_CALENDAR: 'REMOVE_CALENDAR',
  SET_CAL_SUMMARY: 'SET_CAL_SUMMARY',
  SET_COLOR: 'SET_COLOR',
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
  SET_PRIMARY_CAL: 'SET_PRIMARY_CAL'
};

export default CalendarActionTypes;
