const EventActionTypes = {
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  REMOVE_EVENT: 'REMOVE_EVENT',
  WIPE_EVENTS: 'WIPE_EVENTS',
  SET_EV_SUMMARY: 'SET_EV_SUMMARY',
  SET_START_TIME: 'SET_START_TIME',
  SET_END_TIME: 'SET_END_TIME'
};

export default EventActionTypes;
