const EventActionTypes = {
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  REMOVE_EVENT: 'REMOVE_EVENT',

  START_EDITING: 'START_EDITING',
  STOP_EDITING: 'STOP_EDITING',

  SET_TIME_FINDER: 'SET_TIME_FINDER',
  CLEAR_TIME_FINDER: 'CLEAR_TIME_FINDER'
};

export default EventActionTypes;
