const ProviderActionTypes = {
  // CalendarStore
  UPDATE_CALENDAR_LIST: 'PROVIDER_UPDATE_CALENDAR_LIST',
  CREATE_CALENDAR: 'PROVIDER_CREATE_CALENDAR',

  // EventStore
  UPDATE_EVENTS: 'PROVIDER_UPDATE_EVENTS',
  CREATE_EVENT: 'PROVIDER_CREATE_EVENT',
  REMOVE_EVENT: 'PROVIDER_REMOVE_EVENT'
};

export default ProviderActionTypes;
