export const CalendarActionTypes = {
  UPDATE_CALENDARS: 'UPDATE_CALENDARS',
  CREATE_CALENDAR: 'CREATE_CALENDAR',
  REMOVE_CALENDAR: 'REMOVE_CALENDAR',
  WIPE_CALENDARS: 'WIPE_CALENDARS',
  SET_NAME: 'SET_NAME',
  SET_COLOR: 'SET_COLOR',
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY'
};

export const EventActionTypes = {
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  REMOVE_EVENT: 'REMOVE_EVENT',
  WIPE_EVENTS: 'WIPE_EVENTS',
  SET_TITLE: 'SET_TITLE',
  SET_START_TIME: 'SET_START_TIME',
  SET_END_TIME: 'SET_END_TIME'
};
