export const CalendarActionTypes = {
  UPDATE_CALENDARS: 'UPDATE_CALENDARS',
  CREATE_CALENDAR: 'CREATE_CALENDAR',
  REMOVE_CALENDAR: 'REMOVE_CALENDAR',
  WIPE_CALENDARS: 'WIPE_CALENDARS',
  SET_CAL_SUMMARY: 'SET_CAL_SUMMARY',
  SET_COLOR: 'SET_COLOR',
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
  SET_PRIMARY_CAL: 'SET_PRIMARY_CAL'
};

export const EventActionTypes = {
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  REMOVE_EVENT: 'REMOVE_EVENT',
  WIPE_EVENTS: 'WIPE_EVENTS',
  SET_EV_SUMMARY: 'SET_EV_SUMMARY',
  SET_START_TIME: 'SET_START_TIME',
  SET_END_TIME: 'SET_END_TIME'
};

export const ViewActionTypes = {
  OPEN_EVENT_MODAL: 'OPEN_EVENT_MODAL',
  CLOSE_EVENT_MODAL: 'CLOSE_EVENT_MODAL'
};
